/* DO NOT EDIT THIS FILE - it is machine generated */
#include </Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home/include/jni.h>
/* Header for class my_sum_JavaSum */

#ifndef _Included_my_sum_JavaSum
#define _Included_my_sum_JavaSum
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL Java_my_sum_JavaSum_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
